### homepage
GET http://localhost:4000/
content-type: application/json

### getQuestions
GET http://localhost:4000/api/questions
content-type: application/json


### getQuestion
GET http://localhost:4000/api/questions/65a79ebc27837359dc90f5a2
content-type: application/json


